---
format: html
editor: visual
---

# Introduction

As introduced in Section 1.4b, there are numerous forms of connectivity models from the purely functional models using GPS tracking data of animals to structural metrics that quantify the spatial arrangement of different land cover patches. Access to these different models is spread across several different software packages with varying levels of interactive interface. Most exist as package libraries in R and/or Python. Others such as least-cost path models and the Linkage Mapper tool suite are available on interactive GIS platforms like ArcGIS or QGIS.

Some of the most commonly used models today are those that use a cost or resistance surface to model potential movement pathways either from point A to point B or continuously across the full landscape. Models such as

- least-cost path
- randomized shortest paths
- resistant kernels
- Circuitscape and Omniscape

use a resistance raster. While most, including least-cost path and Cricuitscape, require the input of at least one start and end node (points or polygons), Omniscape computes movement from every direction. These models have grown in popularity, in part, because of their relative accessibility to modelers and practitioners for management decisions and the spatial data that are created which can communicate connectivity concepts and concerns to stakeholders.

This slide show provides some additional background on the purpose and functioning of connectivity models: 


