project:
  type: book
  output-dir: _book

book:
  title: "Connectivity Tutorial"
  author:
    - name: "Jeremy Dertien "
      affiliation: "German Centre for Integrative Biodiversity Research (iDiv)"
  date: today
  description: |
      A step-by-step tutorial on....
  repo-url: https://github.com/jdertien/Connectivity_LearningPlatform
  repo-branch: main
  repo-actions: [edit, issue]
  site-url: https://jdertien.github.io/Connectivity_LearningPlatform/
  search: true
  page-navigation: true
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - 1_Conn_Introduction.qmd
    - 2_Model_Background.qmd
    - 3_LCP_QGIS_exercise.qmd
    - 4_LCP_R_exercise.qmd
    - 5_Circuit_exercise_qmd
    - 6_Conclusion.qmd
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    lightbox: true
    code-link: true
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 3
    number-sections: true
    fig-align: center
    fig-cap-location: bottom

execute:
  echo: true
  warning: false
  message: false
  freeze: auto

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
    fig.retina: 2
    fig.align: "center"
