project:
  type: book
  output-dir: _book

book:
  title: "Connecting Landscapes: A Practical Tutorial for Ecological Connectivity Modelling"
  author:
    - name: "Jeremy Dertien, Emmanuel Oceguera-Conchas "
      affiliation: "German Centre for Integrative Biodiversity Research (iDiv) ![](images/idiv-logo.png){width=22px style=\"vertical-align:text-bottom; margin-left:.4em\"} ![](images/NClogo.png){height=22px style=\"vertical-align:text-bottom; margin-left:.5em\"}"
  date: today
  repo-url: https://github.com/jdertien/Connectivity_LearningPlatform
  repo-branch: main
  repo-actions: [edit, issue]
  site-url: https://jdertien.github.io/Connectivity_LearningPlatform/
  search: true
  page-navigation: true
  sidebar:
    style: docked
    background: light
  page-footer:
    left:  |
      [![](images/NClogo.png){height=50px fig-alt="NaturaConnect"}](https://naturaconnect.eu/)
    
    right: |
      :::: {style="max-width:360px; margin-left:auto; text-align:left"}
      ![](images/eu.png){height=52px fig-alt="Funded by the European Union"}

      ::: {style="color:#003399; text-align:justify; font-size:.8rem; margin-top:.6em"}
      NaturaConnect receives funding under the European Union's Horizon Europe
      research and innovation programme under grant agreement number 101060429.
      :::
      ::::
    border: true
  chapters:
    - index.qmd
    - 1_Conn_Introduction.qmd
    - 2_Model_Background.qmd
    - 3_LCP_QGIS_exercise.qmd
    - 4_LCP_R_exercise.qmd
    - 5_Circuit_exercise.qmd
    - 6_Conclusion.qmd
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    lightbox: true
    code-link: true
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 3
    number-sections: true
    fig-align: center
    fig-cap-location: bottom

execute:
  echo: true
  warning: false
  message: false
  freeze: auto

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
    fig.retina: 2
    fig.align: "center"
